### ISSUE TITLE
Add user rating comment exception

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#1148]
```
Exception on /manage/user-rating/add-comment/34 [POST]
Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "./app/decorators.py", line 14, in decorated_function
    return f(*args, **kwargs)
  File "./app/manage/views.py", line 5291, in add_user_rating_comment
    add_feed(user=current_user._get_current_object(), event='回复“{}”给“{}”的评价：{}'.format(user_rating.author.name_alias, user_rating.user.name_alias, to_text(user_rating_comment.body)), category='manage')
AttributeError: 'UserRatingComment' object has no attribute 'body'
```

**Comment by iROCKBUNNY** [comment]
Fixed in #1149
