### ISSUE TITLE
Exception on profile credit forms

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#1197]
```
Exception on /profile/838/credit [GET]
Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "./app/profile/views.py", line 437, in credit
    form=form,
UnboundLocalError: local variable 'form' referenced before assignment
```

**Comment by iROCKBUNNY** [comment]
Fixed in #1201
