### ISSUE TITLE
Exception on `get_geo_info()` due to multiple client IP addresses

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#1572]
```
Exception on / [GET]
Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "./app/views/auth.py", line 38, in before_request
    event='请求访问（来源：{}）'.format(get_geo_info(ip_address=ip_address, show_ip=True)),
  File "./app/utils.py", line 175, in get_geo_info
    response = reader.city(ip_address)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/geoip2/database.py", line 114, in city
    return self._model_for(geoip2.models.City, 'City', ip_address)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/geoip2/database.py", line 195, in _model_for
    record = self._get(types, ip_address)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/geoip2/database.py", line 188, in _get
    record = self._db_reader.get(ip_address)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/maxminddb/reader.py", line 110, in get
    address = compat_ip_address(ip_address)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/maxminddb/compat.py", line 31, in compat_ip_address
    return ipaddress.ip_address(address)
  File "/usr/lib/python3.6/ipaddress.py", line 54, in ip_address
    address)
ValueError: '106.121.109.176, 36.99.38.254' does not appear to be an IPv4 or IPv6 address
```

**Comment by iROCKBUNNY** [comment]
Fixed in #1573
