### ISSUE TITLE
Template not found `locked_user.txt`

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#1599]
```
Exception on /api/login-user/eyJhbGciOiJIUzUxMiIsImlhdCI6MTU1NTU3NTQyMywiZXhwIjoxNTU1NTc5MDIzfQ.eyJlbWFpbCI6ImNoaG5pbmdAeWFob28uY28uanAiLCJwYXNzd29yZCI6IkNobjEyNzkxMDA3MTA3IiwiZGV2aWNlIjoiWjA1In0.0oAT684dLw29DNwexAbaz8BpYFFK2s-8q-2VGSbpQr-_cKnw1c1WKgL98EfWe-ucdjrIrZcQ1SQEMjzjHCbZJw [GET]
Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/views/api.py", line 66, in login_user
    device=data.get('device'),
  File "./app/email.py", line 36, in send_emails
    ) for recipient in recipients])
  File "./app/email.py", line 36, in <listcomp>
    ) for recipient in recipients])
  File "./app/email.py", line 18, in msg_to_dict
    msg.body = render_template(template + '.txt', **kwargs)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: auth/mail/y_vod/locked_user.txt
```

**Comment by iROCKBUNNY** [comment]
Fixed in #1600
