### ISSUE TITLE
Exception on displaying progress due to empty last VB punch

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#1626]
```
Exception on /manage/test/score/gre/85 [GET]
Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "./app/decorators.py", line 17, in decorated_function
    return f(*args, **kwargs)
  File "./app/views/manage.py", line 2663, in test_score
    scores=scores
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/irockbunny/flask/y-english.cn/app/templates/manage/test_score.html", line 2, in top-level template code
    {% import "_macros.html" as macros %}
  File "/home/irockbunny/flask/y-english.cn/app/templates/base.html", line 54, in top-level template code
    {% block content %}{% endblock %}
  File "/home/irockbunny/flask/y-english.cn/app/templates/manage/test_score.html", line 55, in block "content"
    <td><div>进度：<span class="text-blue">{{ score.user.last_vb_punch.section.name }}</span></div>{% with vb_test_scores = score.user.vb_test_scores_ordered %}{% if vb_test_scores.count() %}{% for vb_test_score in vb_test_scores %}<div>{{ vb_test_score.test.abbr }}{% if vb_test_score.retake %} <span class="text-red">[需重修]</span>{% elif vb_test_score.skip %} <span class="text-orange">[跳过]</span>{% endif %}：{{ vb_test_score.score_format }}</div>{% endfor %}{% endif %}{% endwith %}</td>
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'section'
```

**Comment by iROCKBUNNY** [comment]
Fixed in #1627
