### ISSUE TITLE
Database illegal mix of collations error on booking token verification

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#1634]
```
Exception on /manage/rental/rent/booked/step-1 [POST]
Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1267, "Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "./app/decorators.py", line 17, in decorated_function
    return f(*args, **kwargs)
  File "./app/views/manage.py", line 938, in rental_rent_booked_step_1
    booking = Booking.query.filter_by(token=form.token.data).first()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3215, in first
    ret = list(self[0:1])
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3007, in __getitem__
    return list(res)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1267, "Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='")
[SQL: SELECT bookings.user_id AS bookings_user_id, bookings.schedule_id AS bookings_schedule_id, bookings.state_id AS bookings_state_id, bookings.timestamp AS bookings_timestamp, bookings.token AS bookings_token, users_1.id AS users_1_id, users_1.email AS users_1_email, users_1.confirmed AS users_1_confirmed, users_1.role_id AS users_1_role_id, users_1.password_hash AS users_1_password_hash, users_1.registered_at AS users_1_registered_at, users_1.created AS users_1_created, users_1.created_at AS users_1_created_at, users_1.activated AS users_1_activated, users_1.activated_at AS users_1_activated_at, users_1.last_seen_at AS users_1_last_seen_at, users_1.last_seen_ip AS users_1_last_seen_ip, users_1.invalid_login_count AS users_1_invalid_login_count, users_1.deleted AS users_1_deleted, users_1.name AS users_1_name, users_1.name_pinyin AS users_1_name_pinyin, users_1.id_type_id AS users_1_id_type_id, users_1.id_number AS users_1_id_number, users_1.gender_id AS users_1_gender_id, users_1.birthdate AS users_1_birthdate, users_1.mobile AS users_1_mobile, users_1.wechat AS users_1_wechat, users_1.qq AS users_1_qq, users_1.address AS users_1_address, users_1.emergency_contact_name AS users_1_emergency_contact_name, users_1.emergency_contact_mobile AS users_1_emergency_contact_mobile, users_1.emergency_contact_relationship_id AS users_1_emergency_contact_relationship_id, users_1.worked_in_same_field AS users_1_worked_in_same_field, users_1.deformity AS users_1_deformity, users_1.application_specialty AS users_1_application_specialty, users_1.application_country AS users_1_application_country, users_1.application_rank AS users_1_application_rank, users_1.application_degree AS users_1_application_degree, users_1.application_agency AS users_1_application_agency, users_1.time_factor AS users_1_time_factor, users_1.deadline AS users_1_deadline, schedules_1.id AS schedules_1_id, schedules_1.date AS schedules_1_date, schedules_1.period_id AS schedules_1_period_id, schedules_1.peak_time AS schedules_1_peak_time, schedules_1.available AS schedules_1_available, schedules_1.created_at AS schedules_1_created_at, schedules_1.modified_at AS schedules_1_modified_at, schedules_1.modified_by_id AS schedules_1_modified_by_id 
FROM bookings LEFT OUTER JOIN users AS users_1 ON users_1.id = bookings.user_id LEFT OUTER JOIN schedules AS schedules_1 ON schedules_1.id = bookings.schedule_id 
WHERE bookings.token = %(token_1)s 
 LIMIT %(param_1)s]
[parameters: {'token_1': '552非烦9发达7鄂巴方嘚870锕7139吖嗯嗯8啊地6沓出吃擦粉0的额发吃4的側41便1冰7沓12157非常9呵47大风吹279大06発不巴巴52陈鹅56😡吧632', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/2j85)
```

**Comment by iROCKBUNNY** [comment]
Fixed in #1635
