### ISSUE TITLE
Database illegal mix of collations error on email search

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#1636]
```
Exception on /search/email [GET]
Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1267, "Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation 'like'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "./app/decorators.py", line 17, in decorated_function
    return f(*args, **kwargs)
  File "./app/views/search.py", line 73, in email
    .limit(current_app.config['RECORD_PER_QUERY'])\
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3161, in all
    return list(self)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1267, "Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation 'like'")
[SQL: SELECT users.id AS users_id, users.email AS users_email, users.confirmed AS users_confirmed, users.role_id AS users_role_id, users.password_hash AS users_password_hash, users.registered_at AS users_registered_at, users.created AS users_created, users.created_at AS users_created_at, users.activated AS users_activated, users.activated_at AS users_activated_at, users.last_seen_at AS users_last_seen_at, users.last_seen_ip AS users_last_seen_ip, users.invalid_login_count AS users_invalid_login_count, users.deleted AS users_deleted, users.name AS users_name, users.name_pinyin AS users_name_pinyin, users.id_type_id AS users_id_type_id, users.id_number AS users_id_number, users.gender_id AS users_gender_id, users.birthdate AS users_birthdate, users.mobile AS users_mobile, users.wechat AS users_wechat, users.qq AS users_qq, users.address AS users_address, users.emergency_contact_name AS users_emergency_contact_name, users.emergency_contact_mobile AS users_emergency_contact_mobile, users.emergency_contact_relationship_id AS users_emergency_contact_relationship_id, users.worked_in_same_field AS users_worked_in_same_field, users.deformity AS users_deformity, users.application_specialty AS users_application_specialty, users.application_country AS users_application_country, users.application_rank AS users_application_rank, users.application_degree AS users_application_degree, users.application_agency AS users_application_agency, users.time_factor AS users_time_factor, users.deadline AS users_deadline 
FROM users INNER JOIN roles ON roles.id = users.role_id 
WHERE roles.name != %(name_1)s AND users.created = true AND users.deleted = false AND (users.name LIKE %(name_2)s OR users.name_pinyin LIKE %(name_pinyin_1)s OR users.email LIKE %(email_1)s) ORDER BY users.last_seen_at DESC 
 LIMIT %(param_1)s]
[parameters: {'name_1': '开发人员', 'name_2': '%阿425008944恶8⃣️方7136451版4994752440帆船03🚖7鹅0519法付费报道称83但3啊9二层埃尔165白饿打成锕2白到9938268爸3的俄4599策发别94417%', 'name_pinyin_1': '%阿425008944恶8⃣️方7136451版4994752440帆船03🚖7鹅0519法付费报道称83但3啊9二层埃尔165白饿打成锕2白到9938268爸3的俄4599策发别94417%', 'email_1': '%阿425008944恶8⃣️方7136451版4994752440帆船03🚖7鹅0519法付费报道称83但3啊9二层埃尔165白饿打成锕2白到9938268爸3的俄4599策发别94417%', 'param_1': 50}]
(Background on this error at: http://sqlalche.me/e/2j85)
```

**Comment by iROCKBUNNY** [comment]
Fixed in #1637
