### ISSUE TITLE
Database duplicate entry error on granting initial lesson access during user activation

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#1647]
```
Exception on /auth/activate [POST]
Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '2005-1' for key 'PRIMARY'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/views/auth.py", line 417, in activate
    user.activate(new_password=form.password.data)
  File "./app/models.py", line 6253, in activate
    self.grant_initial_lesson_access()
  File "./app/models.py", line 5930, in grant_initial_lesson_access
    type_id=LessonAccessType.query.filter_by(name='正常研修').first().id,
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3215, in first
    ret = list(self[0:1])
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3007, in __getitem__
    return list(res)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3316, in __iter__
    self.session._autoflush()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1587, in _autoflush
    util.raise_from_cause(e)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1576, in _autoflush
    self.flush()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2451, in flush
    self._flush(objects)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2549, in _flush
    flush_context.execute()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1066, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/irockbunny/flask/y-english.cn/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(pymysql.err.IntegrityError) (1062, "Duplicate entry '2005-1' for key 'PRIMARY'")
[SQL: INSERT INTO lesson_accesses (user_id, lesson_id, type_id, created_at, modified_at, modified_by_id) VALUES (%(user_id)s, %(lesson_id)s, %(type_id)s, %(created_at)s, %(modified_at)s, %(modified_by_id)s)]
[parameters: {'user_id': 2005, 'lesson_id': 1, 'type_id': 1, 'created_at': datetime.datetime(2019, 5, 29, 13, 27, 41, 161965), 'modified_at': datetime.datetime(2019, 5, 29, 13, 27, 41, 161974), 'modified_by_id': 2005}]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by iROCKBUNNY** [comment]
Fixed in #1648
