### ISSUE TITLE
Restrict study plan editing to activated users

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#422]
```
[2017-06-28 14:21:53,732] ERROR in app: Exception on /manage/study-plan/edit/215 [GET]
Traceback (most recent call last):
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "./app/decorators.py", line 14, in decorated_function
    return f(*args, **kwargs)
  File "./app/manage/views.py", line 5618, in edit_study_plan
    form.deadline.data = user.deadline or user.due_date
  File "./app/models.py", line 4103, in due_date
    if self.due_time is not None:
  File "./app/models.py", line 4092, in due_time
    year = self.activated_at.year + (self.activated_at.month + extended_months) / 12
AttributeError: 'NoneType' object has no attribute 'year'
```

**Comment by iROCKBUNNY** [comment]
Fixed in #427
