### ISSUE TITLE
Duplicate activation initial punch

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#423]
```
[2017-06-27 16:51:49,914] ERROR in app: Exception on /auth/activate [POST]
Traceback (most recent call last):
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/auth/views.py", line 341, in activate
    send_emails([user.email for user in User.users_can(u'管理用户').all()], u'新用户：%s' % (new_user.name_alias), 'auth/mail/new_user', user=new_user)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2854, in __iter__
    self.session._autoflush()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1407, in _autoflush
    util.raise_from_cause(e)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1397, in _autoflush
    self.flush()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2255, in _flush
    flush_context.execute()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 799, in _emit_insert_statements
    execute(statement, multiparams)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (pymysql.err.IntegrityError) (1062, u"Duplicate entry '289-1' for key 'PRIMARY'") [SQL: u'INSERT INTO punches (user_id, section_id, timestamp) VALUES (%(user_id)s, %(section_id)s, %(timestamp)s)'] [parameters: {'timestamp': datetime.datetime(2017, 6, 27, 8, 6, 45, 622961), 'user_id': 289, 'section_id': 1}]
```

**Comment by iROCKBUNNY** [comment]
Fixed in #427
