### ISSUE TITLE
Log email timeout exception

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#424]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 928, in emit
    smtp = smtplib.SMTP(self.mailhost, port, timeout=self._timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 317, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python2.7/smtplib.py", line 365, in getreply
    + str(e))
SMTPServerDisconnected: Connection unexpectedly closed: timed out
```

**Comment by iROCKBUNNY** [comment]
Fixed in #427
