### ISSUE TITLE
Reset password exception

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#469]
```
Exception on /auth/password/reset/eyJhbGciOiJIUzI1NiIsImV4cCI6MTQ5OTEwMzU0NCwiaWF0IjoxNDk5MDk5OTQ0fQ.eyJyZXNldCI6MjM3fQ.oxvA1fuZQ62HzASM-zIuZEaB_QPOZacAXVRRpeuMDsc [GET]
Traceback (most recent call last):
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/auth/views.py", line 424, in reset_password
    return render_template('auth/reset_password.html', form=form)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/proj.d/y-english.org/app/templates/auth/reset_password.html", line 2, in top-level template code
    {% import "_macros.html" as macros %}
  File "/home/irockbunny/flask/proj.d/y-english.org/app/templates/base.html", line 68, in top-level template code
    {% block body %}
  File "/home/irockbunny/flask/proj.d/y-english.org/app/templates/base.html", line 394, in block "body"
    {% block page_masthead %}
  File "/home/irockbunny/flask/proj.d/y-english.org/app/templates/auth/reset_password.html", line 15, in block "page_masthead"
    <form id="reset-password" action="{{ url_for('auth.reset_password') }}" method="POST" class="ui inverted form">
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'auth.reset_password'. Did you forget to specify values ['token']?
```

**Comment by iROCKBUNNY** [comment]
Fixed in #456
