### ISSUE TITLE
Remove GRE/GMAT/TOEFL score actions on profile page

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#489]
```
Exception on /manage/test/score/edit/gre/240 [GET]
Traceback (most recent call last):
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "./app/decorators.py", line 14, in decorated_function
    return f(*args, **kwargs)
  File "./app/manage/views.py", line 2632, in edit_test_score
    return render_template('manage/edit_test_score.html', test_type=test_type, form=form, score=score)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/proj.d/y-english.org/app/templates/manage/edit_test_score.html", line 2, in top-level template code
    {% import "_macros.html" as macros %}
  File "/home/irockbunny/flask/proj.d/y-english.org/app/templates/base.html", line 68, in top-level template code
    {% block body %}
  File "/home/irockbunny/flask/proj.d/y-english.org/app/templates/base.html", line 398, in block "body"
    {% block page_content %}
  File "/home/irockbunny/flask/proj.d/y-english.org/app/templates/manage/edit_test_score.html", line 226, in block "page_content"
    <a class="ui button loading-trigger" href="{{ request.args.get('next') or url_for('manage.test_score', test_type=test_type, id=score.test.id) }}">取消</a>
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1766, in build
    rv = self._partial_build(endpoint, values, method, append_unknown)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1681, in _partial_build
    append_unknown)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1689, in _partial_build
    rv = rule.build(values, append_unknown)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/werkzeug/routing.py", line 806, in build
    add(self._converters[data].to_url(values[data]))
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1026, in to_url
    value = self.num_convert(value)
UndefinedError: 'None' has no attribute 'id'
```

**Comment by iROCKBUNNY** [comment]
Fixed in #491
