### ISSUE TITLE
Unfinished tasks exception on profile overview page

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#534]
```
Exception on /profile/119 [GET]
Traceback (most recent call last):
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "./app/main/views.py", line 289, in profile
    announcements=announcements
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/proj.d/y-english.org/app/templates/profile.html", line 2, in top-level template code
    {% import "_macros.html" as macros %}
  File "/home/irockbunny/flask/proj.d/y-english.org/app/templates/base.html", line 68, in top-level template code
    {% block body %}
  File "/home/irockbunny/flask/proj.d/y-english.org/app/templates/base.html", line 444, in block "body"
    {% block page_content %}
  File "/home/irockbunny/flask/proj.d/y-english.org/app/templates/profile.html", line 404, in block "page_content"
    {% if show_profile_overview %}
  File "./app/models.py", line 5023, in unfinished_tasks
    if lesson.stage.name == u'VB L6-9':
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by iROCKBUNNY** [comment]
Fixed in #535
