### ISSUE TITLE
Booking Y-GRE Exception

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#546]
```
Exception on /book/y-gre/unbook/309 [GET]
Traceback (most recent call last):
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/irockbunny/flask/proj.d/y-english.org/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "./app/decorators.py", line 14, in decorated_function
    return f(*args, **kwargs)
  File "./app/book/views.py", line 377, in unbook_y_gre
    send_email(waited_booking.user.email, u'您已成功预约%s %s的%s课程' % (waited_booking.schedule.date, waited_booking.schedule.period.alias2, waited_booking.schedule.period.name), 'book/mail/booking', booking=booking)
NameError: global name 'booking' is not defined
```

**Comment by iROCKBUNNY** [comment]
Fixed in #548
