### ISSUE TITLE
Add assignment score exception

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#838]
```
Exception on /profile/662/score [POST]
Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "./app/profile/views.py", line 241, in score
    flash('已添加作业记录：%s' % score.alias, category='success')
  File "./app/models.py", line 1061, in alias
    return '%s %s %s' % (self.user.name_alias, self.assignment.name, self.grade.name)
AttributeError: 'NoneType' object has no attribute 'name_alias'
```

**Comment by iROCKBUNNY** [comment]
Fixed in #839
