### ISSUE TITLE
Inbox typo exception

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#855]
```
Exception on /inbox/message/118 [GET]
Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "./app/inbox/views.py", line 94, in message
    db.sesscion.commit()
AttributeError: 'SQLAlchemy' object has no attribute 'sesscion'
```

**Comment by iROCKBUNNY** [comment]
Fixed in #856
