### ISSUE TITLE
Treatment view exceptions

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#968]
```
Exception on /treat/vb/assignment [GET]
Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "./app/decorators.py", line 14, in decorated_function
    return f(*args, **kwargs)
  File "./app/treat/views.py", line 1058, in vb_assignment
    scores=scores
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/irockbunny/flask/y-english.org/app/templates/treat/vb/assignment.html", line 1, in top-level template code
    {% extends "treat/vb/base.html" %}
  File "/home/irockbunny/flask/y-english.org/app/templates/treat/vb/base.html", line 2, in top-level template code
    {% import "_macros.html" as macros %}
  File "/home/irockbunny/flask/y-english.org/app/templates/base.html", line 541, in top-level template code
    {% block content %}{% endblock %}
  File "/home/irockbunny/flask/y-english.org/app/templates/treat/vb/base.html", line 25, in block "content"
    {% block vb_content %}{% endblock %}
  File "/home/irockbunny/flask/y-english.org/app/templates/treat/vb/assignment.html", line 38, in block "vb_content"
    <a class="ui {% if score.feedback %}grey {% endif %}button loading-trigger" href="{{ url_for('manage.toggle_assignment_score_feedback', id=score.id, next=url_for('treat.assignment')) }}" data-tooltip="标记“{% if score.feedback %}未反馈{% else %}已反馈{% endif %}”" data-position="top center" data-inverted=""><i class="treatment icon"></i></a>
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'treat.assignment'. Did you mean 'treat.vb_assignment' instead?
```
```
Exception on /manage/test/score/toggle-feedback/1246 [GET]
Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "./app/decorators.py", line 14, in decorated_function
    return f(*args, **kwargs)
  File "./app/manage/views.py", line 2627, in test_score
    pagination = query.paginate(page, per_page=current_app.config['RECORD_PER_PAGE'], error_out=False)
UnboundLocalError: local variable 'query' referenced before assignment
```

**Comment by iROCKBUNNY** [comment]
Fixed in #969
