### ISSUE TITLE
Add test date exception

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-System#993]
```
Exception on /manage/test [POST]
Traceback (most recent call last):
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/irockbunny/flask/y-english.org/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "./app/decorators.py", line 14, in decorated_function
    return f(*args, **kwargs)
  File "./app/manage/views.py", line 2183, in test
    flash('已添加考试：%s' % test_date.alias, category='success')
  File "./app/models.py", line 1722, in alias
    return '%s %s' % (self.type.name, self.date.strftime('%Y-%m-%d'))
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by iROCKBUNNY** [comment]
Fixed in #994
